### ISSUE TITLE
Integrated support for locking

### ISSUE THREAD

**Issue by joakimnordling** [ioxiocom/firedantic#19]
Would be nice to have support for locking to prevent race conditions when loading and modifying models.

This could likely be done somewhat similar to how it's done in arangodantic, that implements `lock_and_load`, `lock_and_reload`, `reload` and `get_lock` methods on the model class.

Arangodantic uses [Shylock](https://github.com/lietu/shylock) for managing the locks. It does not yet have support for firedantic, but could easily be extended with support for it.

**Comment by lietu** [comment]
In case of Firestore the common practice is using transactions as requested in https://github.com/ioxiocom/firedantic/issues/36 - closing this in favor of that one.
